services:
  frontend:
    build: frontend/.
    ports:
      - "8988:8000"
    restart: always
  api:
    build: api/.
    restart: always
    ports:
      - "8981:8001"
    volumes:
      - database:/database
  scraper:
    build: scraper/.
    volumes:
      - database:/database
volumes:
  database:
